### ISSUE TITLE
Notification Rollout & Implementation [Tracking]

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-autoupdate#43]
TO-DO:
* [ ] Do a tighter match on the notification output so it only updates the intended part of the log, rather than getting a little overly enthusiastic and sharing the wrong lines.

* [ ] Consider utilising `brew cleanup` or tweak this tool itself to periodically remove the log file so it doesn't become too large in size and/or increasingly slow to machine-read.

* [ ] Consider adding a notification for the start of the update process, i.e. `Homebrew Autoupdate Starting` or such.

* [ ] Consider adding a notification for background failures, even if we don't get too elaborate about it. This command logs the entire output to a file anyway, so it'd be easy enough to alert the user to the fact the command failed and to look at the log file to work out why if we wanted to keep it barebones. **Ref: https://github.com/Homebrew/homebrew-autoupdate/issues/42.**

* [ ] Investigate whether the above can be achieved using the one AppleScript applet or whether because of the somewhat limited & finicky nature of applets I'd need to add unique applets for each case (which wouldn't really be a big burden, but isn't ideal).

* [ ] Fully deprecate `terminal-notifier`, as it seems to be dead upstream at this point and provides a pretty suboptimal experience compared to native macOS notifications. This might involve waiting until macOS 12 _(assuming whatever comes after Big Sur is called macOS 12)_ so that there's at least two recent versions of macOS supported by the new notifier.

This issue supersedes https://github.com/Homebrew/homebrew-autoupdate/issues/25, https://github.com/Homebrew/homebrew-autoupdate/issues/15 & https://github.com/Homebrew/homebrew-autoupdate/issues/42.

**Comment by buschtoens** [comment]
I've encountered a bug: #71 The new [`brew-autoupdate.app`](https://github.com/Homebrew/homebrew-autoupdate/tree/master/notifier/brew-autoupdate.app/Contents) notifier "steals the focus" from the prior window when displaying a notification.

**Comment by DomT4** [comment]
I've been fairly generous on the timeline (IMO) but moves towards `Fully deprecate terminal-notifier, as it seems to be dead upstream at this point and provides a pretty suboptimal experience compared to native macOS notifications` are underway, which will allow/help facilitate adding more features to the newer style of notification without so much code sitting around for `terminal-notifier` support: https://github.com/Homebrew/homebrew-autoupdate/commit/2574d2332d0e223150c788d36870ded4e0943574, https://github.com/Homebrew/homebrew-autoupdate/commit/2761e385524f8a3cf3645058fb24199d0e73f3fd.

**Comment by buschtoens** [comment]
@erikw I'll try to answer your first question:

> Would it be possible to make it so that the icon of `brew-autoupdate.app` does not show up in the Dock? I find it a bit disruptive to have visually things going on in the dock at the same time as notification in the uppe right corner. Ideally only the notification should pop up, no icon in the Dock.
> 
> I managed to capture it in a screen shot this time:
>
> ![Screen Shot 2022-04-19 at 18 39 26](https://user-images.githubusercontent.com/175286/164054145-8733a653-0d30-4077-80c4-00ded4280bf8.png)

If you check my PR #72, you can see that I added the `-g` flag to launch the notifier in the background in order to not steal the focus from the current foreground application.

`man open` tells me that besides `-g`, there also is a `-j` flag:

> - **`-g`** Do not bring the application to the foreground.
> - **`-j`** Launches the app hidden.

You could try adding the `-j` flag in addition to `-g` to prevent the icon from showing up in the dock.

**Comment by erikw** [comment]
@buschtoens thanks, this looked promising from the manual. Unfortunately the command

```console
$ /usr/bin/open -g -j /usr/local/Homebrew/Library/Taps/homebrew/homebrew-autoupdate/notifier/brew-autoupdate.app
```
still shows the icon in the Dock in the same way. I also tried with using just `-j` which gave the same result. I'm on macOS `12.3.2` BTW.

From the first post in this issue

> * using the one AppleScript applet

I understand this as `brew-autoupdate.app` is a wrapper around and AppleScript? For applications in Obj-C and Swift I found some resources ([#1](https://stackoverflow.com/questions/54500071/how-can-i-prevent-an-executable-icon-from-appearing-in-the-dock) [#2](https://stackoverflow.com/questions/54500071/how-can-i-prevent-an-executable-icon-from-appearing-in-the-dock)) showing how to hide the Dock icon, however these would not apply when the main application is an AppleScript I guess.

When I searched for solutions I [found](https://www.addictivetips.com/mac-os/how-to-hide-the-dock-icon-for-any-mac-app-while-it-is-running/) that one can add to `brew-autoupdate.app/Contents/Info.plist`
```xml
  <key>LSUIElement</key>
  <string>1</string>
```
This indeed hid the icon in the Dock, but unfortunately no notification was shown either :(

Any other ideas?
